# import RPi.GPIO as GPIO


''' CRUZAMENTO 1  '''
SEMAFORO_1_VERDE_C1 = 1
SEMAFORO_1_AMARELO_C1 = 26
SEMAFORO_1_VERMELHO_C1 = 21

SEMAFORO_2_VERDE_C1 = 20
SEMAFORO_2_AMARELO_C1 = 16
SEMAFORO_2_VERMELHO_C1 = 12

BOTAO_PEDESTRE_1_C1 = 8
BOTAO_PEDESTRE_2_C1 = 7

SENSOR_PASSAGEM_1_C1 = 14
SENSOR_PASSAGEM_2_C1 = 15

SENSOR_VELOCIDADE_1_A_C1 = 18
SENSOR_VELOCIDADE_1_B_C1 = 23

SENSOR_VELOCIDADE_2_A_C1 = 24
SENSOR_VELOCIDADE_2_B_C1 = 25

''' CRUZAMENTO 2  '''
SEMAFORO_1_VERDE_C2 = 2
SEMAFORO_1_AMARELO_C2 = 3
SEMAFORO_1_VERMELHO_C2 = 11

SEMAFORO_2_VERDE_C2 = 0
SEMAFORO_2_AMARELO_C2 = 15
SEMAFORO_2_VERMELHO_C2 = 6

BOTAO_PEDESTRE_1_C2 = 10
BOTAO_PEDESTRE_2_C2 = 9

SENSOR_PASSAGEM_1_C2 = 4
SENSOR_PASSAGEM_2_C2 = 17 

SENSOR_VELOCIDADE_1_A_C2 = 27 
SENSOR_VELOCIDADE_1_B_C2 = 22

SENSOR_VELOCIDADE_2_A_C2 = 13
SENSOR_VELOCIDADE_2_B_C2 = 19

outputs = [
    SEMAFORO_1_VERDE_C1,
    SEMAFORO_1_AMARELO_C1,
    SEMAFORO_1_VERMELHO_C1,
    SEMAFORO_1_VERDE_C2,
    SEMAFORO_1_AMARELO_C2,
    SEMAFORO_1_VERMELHO_C2,
    SEMAFORO_2_VERDE_C1,
    SEMAFORO_2_AMARELO_C1,
    SEMAFORO_2_VERMELHO_C1,
    SEMAFORO_2_VERDE_C2,
    SEMAFORO_2_AMARELO_C2,
    SEMAFORO_2_VERMELHO_C2,
]

inputs_botao = [
    BOTAO_PEDESTRE_1_C1,  
    BOTAO_PEDESTRE_2_C1,  
    BOTAO_PEDESTRE_1_C2,
    BOTAO_PEDESTRE_2_C2,  
]

intputs_sensores = [
    SENSOR_PASSAGEM_1_C1,
    SENSOR_PASSAGEM_2_C1,
    SENSOR_PASSAGEM_1_C2, 
    SENSOR_PASSAGEM_2_C2, 
    SENSOR_VELOCIDADE_1_A_C1,
    SENSOR_VELOCIDADE_1_B_C1,
    SENSOR_VELOCIDADE_1_A_C2, 
    SENSOR_VELOCIDADE_1_B_C2,
    SENSOR_VELOCIDADE_2_A_C1,
    SENSOR_VELOCIDADE_2_B_C1,
    SENSOR_VELOCIDADE_2_A_C2,
    SENSOR_VELOCIDADE_2_B_C2,
]


def config_gpio():
    # GPIO.setup(outputs, GPIO.OUT)
    # GPIO.setup(inputs_botao, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
    # GPIO.setup(intputs_sensores, GPIO.IN, pull_up_down=GPIO.PUD_UP)


